### omgang read
GET http://localhost/bjornagain/carcscores/carcscores/omgang/read.php HTTP/1.1
content-type: application/json


### omgang read last ID
GET http://localhost/bjornagain/carcscores/carcscores/omgang/readLastID.php HTTP/1.1
content-type: application/json


### omgang create
POST http://localhost/bjornagain/carcscores/carcscores/omgang/create.php HTTP/1.1
content-type: application/json
{
    "OmgangID": "NULL"
}


### resultat read
GET http://localhost/bjornagain/carcscores/carcscores/resultat/read.php HTTP/1.1
content-type: application/json

### resultat readcomplex
GET http://localhost/bjornagain/carcscores/carcscores/resultat/readcomplex.php HTTP/1.1
content-type: application/json


### resultat create
POST http://localhost/bjornagain/carcscores/carcscores/resultat/create.php HTTP/1.1
content-type: application/json
{
    "ResultatID": "NULL",
    "ResOmgRef":"109",
    "ResSpillerRef":"3",
    "ResPoeng":"163"
}


### resultat create multiple
### virker ikke, under arbeid
POST http://localhost/bjornagain/carcscores/carcscores/resultat/createmulti.php  HTTP/1.1
content-type: application/json        


### spiller read
GET http://localhost/bjornagain/carcscores/carcscores/spiller/read.php HTTP/1.1
content-type: application/json


### spiller readagain
GET http://localhost/bjornagain/carcscores/carcscores/spiller/readagain.php HTTP/1.1
content-type: application/json


### spiller test_objects
GET http://localhost/bjornagain/carcscores/carcscores/spiller/test_objects.php HTTP/1.1
content-type: application/json



### spiller create
POST http://localhost/bjornagain/carcscores/carcscores/spiller/create.php HTTP/1.1
content-type: application/json
{
    "SpillerID": "NULL",
    "SpillerFornavn":"Testersen"
}


