
POST http://localhost/bjornagain/carcscores/carcscores/resultat/create.php HTTP/1.1
content-type: application/json

{
    "ResultatID": "NULL",
    "ResOmgRef":"106",
    "ResSpillerRef":"3",
    "ResPoeng":"163"
}
